<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <!-- 全局抑制所有 NU1701 警告 -->
	  <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dragablz" Version="0.0.3.234" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseProj\CS.Base.csproj" />
    <ProjectReference Include="..\CSK.Core\CSK.Core.csproj" />
    <ProjectReference Include="C:\Users\k2206\Desktop\LiveCharts2官网示例\LiveCharts2\src\LiveChartsCore\LiveChartsCore.csproj" />
    <ProjectReference Include="C:\Users\k2206\Desktop\LiveCharts2官网示例\LiveCharts2\src\skiasharp\LiveChartsCore.SkiaSharp.WPF\LiveChartsCore.SkiaSharpView.WPF.csproj" />
  </ItemGroup>

</Project>
