<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\AnimaPng.png" />
    <None Remove="Resource\LightPng.png" />
    <None Remove="Resource\PhonePng.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseProj\CS.Base.csproj" />
    <ProjectReference Include="..\CS.Communication\CS.Communication.csproj" />
    <ProjectReference Include="..\CSK.Core\CSK.Core.csproj" />
    <ProjectReference Include="..\DataAnalasisProj\CS.DataAnalysis.csproj" />
    <ProjectReference Include="..\Database\CS.Database.csproj" />
    <ProjectReference Include="..\LoggerProj\LoggerProj.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dragablz" Version="0.0.3.234" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resource\AnimaPng.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\LightPng.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\PhonePng.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
