<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BaseProj\CS.Base.csproj" />
    <ProjectReference Include="..\CSK.Core\CSK.Core.csproj" />
    <ProjectReference Include="..\LoggerProj\LoggerProj.csproj" />
  </ItemGroup>

</Project>
