// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(CSK_DBContext))]
    [Migration("20251230063318_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Database.Model.ProducttProductionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QualityInspectionResult")
                        .HasColumnType("bit");

                    b.Property<float>("TimeConsumed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("T_ProducttProductionRecords", (string)null);
                });

            modelBuilder.Entity("Database.Model.ProducttProductionRecord", b =>
                {
                    b.OwnsOne("Database.Structs.ProductEnvironmentPraram", "Param", b1 =>
                        {
                            b1.Property<int>("ProducttProductionRecordId")
                                .HasColumnType("int");

                            b1.Property<float>("Humidity")
                                .HasColumnType("real");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real");

                            b1.HasKey("ProducttProductionRecordId");

                            b1.ToTable("T_ProducttProductionRecords");

                            b1.WithOwner()
                                .HasForeignKey("ProducttProductionRecordId");
                        });

                    b.Navigation("Param");
                });
#pragma warning restore 612, 618
        }
    }
}
