// <auto-generated />
using CS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CS.Database.Migrations
{
    [DbContext(typeof(CSK_DBContext))]
    [Migration("20260106100002_addTime")]
    partial class addTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CS.Database.Entity.LineProductionRecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<float>("ProductConsumed")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("T_LineProductionRecords", (string)null);
                });

            modelBuilder.Entity("CS.Database.Entity.MaterialRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("T_MaterialRecords", (string)null);
                });

            modelBuilder.Entity("CS.Database.Entity.ProducttProductionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QualityInspectionResult")
                        .HasColumnType("bit");

                    b.Property<float>("TimeConsumed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("T_ProducttProductionRecords", (string)null);
                });

            modelBuilder.Entity("CS.Database.Entity.LineProductionRecord", b =>
                {
                    b.OwnsOne("CS.Database.Structs.ProductOutput", "ProductsOutput", b1 =>
                        {
                            b1.Property<int>("LineProductionRecordID")
                                .HasColumnType("int");

                            b1.Property<int>("Product_1")
                                .HasColumnType("int");

                            b1.Property<int>("Product_2")
                                .HasColumnType("int");

                            b1.Property<int>("Product_3")
                                .HasColumnType("int");

                            b1.Property<int>("Product_4")
                                .HasColumnType("int");

                            b1.Property<int>("Product_5")
                                .HasColumnType("int");

                            b1.HasKey("LineProductionRecordID");

                            b1.ToTable("T_LineProductionRecords");

                            b1.WithOwner()
                                .HasForeignKey("LineProductionRecordID");
                        });

                    b.OwnsOne("CS.Database.Structs.ProductQualifiedRate", "ProductsRate", b1 =>
                        {
                            b1.Property<int>("LineProductionRecordID")
                                .HasColumnType("int");

                            b1.Property<float>("Product1Rate")
                                .HasColumnType("real");

                            b1.Property<float>("Product2Rate")
                                .HasColumnType("real");

                            b1.Property<float>("Product3Rate")
                                .HasColumnType("real");

                            b1.Property<float>("Product4Rate")
                                .HasColumnType("real");

                            b1.Property<float>("Product5Rate")
                                .HasColumnType("real");

                            b1.HasKey("LineProductionRecordID");

                            b1.ToTable("T_LineProductionRecords");

                            b1.WithOwner()
                                .HasForeignKey("LineProductionRecordID");
                        });

                    b.Navigation("ProductsOutput");

                    b.Navigation("ProductsRate");
                });

            modelBuilder.Entity("CS.Database.Entity.MaterialRecord", b =>
                {
                    b.OwnsOne("CS.Database.Structs.QualityControl", "QualityPArams", b1 =>
                        {
                            b1.Property<int>("MaterialRecordId")
                                .HasColumnType("int");

                            b1.Property<float>("Height")
                                .HasColumnType("real");

                            b1.Property<bool>("IsBurred")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsDeformed")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsQualified")
                                .HasColumnType("bit");

                            b1.Property<float>("Weight")
                                .HasColumnType("real");

                            b1.Property<float>("Width")
                                .HasColumnType("real");

                            b1.HasKey("MaterialRecordId");

                            b1.ToTable("T_MaterialRecords");

                            b1.WithOwner()
                                .HasForeignKey("MaterialRecordId");
                        });

                    b.Navigation("QualityPArams");
                });

            modelBuilder.Entity("CS.Database.Entity.ProducttProductionRecord", b =>
                {
                    b.OwnsOne("CS.Database.Structs.ProductEnvironmentPraram", "Param", b1 =>
                        {
                            b1.Property<int>("ProducttProductionRecordId")
                                .HasColumnType("int");

                            b1.Property<float>("Humidity")
                                .HasColumnType("real")
                                .HasColumnName("Param_Humidity");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("Param_Temperature");

                            b1.HasKey("ProducttProductionRecordId");

                            b1.ToTable("T_ProducttProductionRecords");

                            b1.WithOwner()
                                .HasForeignKey("ProducttProductionRecordId");
                        });

                    b.Navigation("Param");
                });
#pragma warning restore 612, 618
        }
    }
}
